name: Github to AWS CodeCommit Sync
description: 'Synchronize from GitHub to CodeCommit via GitHub Actions using IAM credentials.'
author: 'genoMichele'
branding:
  icon: terminal
  color: yellow
inputs:
  codecommit_url:
    description: CodeCommit url.
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
